### ISSUE TITLE
设置页面无法显示已更改的选项

### ISSUE THREAD

**Issue by Doraemonsan** [jiangweifang/wp-live2d#1]
## 正常情况下每个选项都应该有默认设置，或已经更改的选项前面的图标会被颜色填充，但是目前v1.7.7-1.7.9版本设置并保存后所有非文本框选项都会被重置为空，但是实际保存的设置都有生效。
如图：
![image](https://user-images.githubusercontent.com/21234683/211150975-b63bfa26-b4be-4d47-a653-837a869b654b.png)
# 其他信息：
插件版本：1.7.9
WP版本：6.1.1
PHP版本：8.0.22
NGINX版本：1.14.1
数据库版本：MariaDB 10.3.28

**Comment by jiangweifang** [comment]
抱歉给您带来麻烦了, 有可能是在修改结构的时候,没有对跨版本进行测试导致的. 如果可以请完全停用插件后重试
