### ISSUE TITLE
付费用户怎么放上自己的moc3模型

### ISSUE THREAD

**Issue by xiehongkai** [jiangweifang/wp-live2d#10]
想请教一下，付费用户怎么放上自己的moc3模型？看了文档，无从下手，且创意工坊的模型下载也不可用，目前存在api报错功能

**Comment by jiangweifang** [comment]
你可以加我QQ我可以详细和你说一下。85838607

**Comment by xiehongkai** [comment]
您好，已添加，您接受一下&nbsp;


半梦半醒、半忧伤
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月10日(星期一) 中午1:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jiangweifang/wp-live2d] 付费用户怎么放上自己的moc3模型 (Issue #10)





 
你可以加我QQ我可以详细和你说一下。85838607

**Comment by hatsuyuki280** [comment]
> 你可以加我QQ我可以详细和你说一下。85838607

你好，我有相同的问题需要帮助，已经申请添加你的QQ了，希望可以通过一下，
或者如果有相关的文档可以给我参考就更好了。

**Comment by jiangweifang** [comment]
> > 你可以加我QQ我可以详细和你说一下。85838607
> 
> 你好，我有相同的问题需要帮助，已经申请添加你的QQ了，希望可以通过一下， 或者如果有相关的文档可以给我参考就更好了。

抱歉 我没有收到您的申请, 可以再试一次吗?
