### ISSUE TITLE
Live2D SDK加载缓慢

### ISSUE THREAD

**Issue by baysonfox** [jiangweifang/wp-live2d#11]
1.7.5版 加载Live2D SDK及其缓慢，可以使用jsDelivr+GitHub辅助加载.
![image](https://user-images.githubusercontent.com/23008133/91654532-2274b500-eadc-11ea-86ed-57031e7ae997.png)

**Comment by jiangweifang** [comment]
老用户啊~哈哈，是这样的 live2dcubismcore.min.js 在软件许可协议上是不允许被分发的，就是说未经授权不可以复制到其他地方，所以我只能使用官网地址，官网没有办法进行jsDelivr加速，如果你无法忍受，可以去官网下载其文件https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js 保存到自己的git或本地，通过调整https://github.com/jiangweifang/wp-live2d/blob/master/wordpress-live2d.php 第27行，可以修改加载路径

由于不允许被分发，所以以上修改出现的任何法律问题由您本人自行承担，感谢您的支持！

**Comment by jiangweifang** [comment]
软件许可协议请见https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_en.html 
5.3.2和第六项下的条款

**Comment by jiangweifang** [comment]
对于此项我也有其他的绕行方案，我可能需要研究一下具体如何处理，处理完成后会对功能进行#11标记
