### ISSUE TITLE
GPT发送按钮位置不对，似乎也无法使用

### ISSUE THREAD

**Issue by SuNine520** [jiangweifang/wp-live2d#11]
在iOS15.4 (19E241) 的Safari中，网页无论怎么缩放，gpt的发送按钮始终在文本框的下面，且点击发送似乎没反应
![IMG_8975](https://github.com/jiangweifang/wp-live2d/assets/108531550/92b751f8-24ba-4bf3-9939-51dc85cff992)

**Comment by V4444** [comment]
是的，会报错。
![image](https://github.com/jiangweifang/wp-live2d/assets/66543869/a8fd2da7-9454-4110-8f2c-ba63fef320fa)

![image](https://github.com/jiangweifang/wp-live2d/assets/66543869/e5dcdb2c-d8e9-4543-957e-04559f96e884)

**Comment by jiangweifang** [comment]
> 是的，会报错。 ![image](https://user-images.githubusercontent.com/66543869/238891050-a8fd2da7-9454-4110-8f2c-ba63fef320fa.png)
> 
> ![image](https://user-images.githubusercontent.com/66543869/238890658-e5dcdb2c-d8e9-4543-957e-04559f96e884.png)

这是因为我今天启用了ECDN加速, 可能某些情况下会导致signalR 无法连接服务器. 强制刷新后应该会恢复, 最近几天我再研究一下具体原因.

**Comment by jiangweifang** [comment]
此问题已解决, 由于腾云ECDN默认断开WS时间过短导致, 已正常至60秒.
