### ISSUE TITLE
是否能添加通过已部署的api读取model3.json的功能

### ISSUE THREAD

**Issue by ChamberyChang** [jiangweifang/wp-live2d#13]
我在部署[fghrsh的live2d_api项目](https://github.com/fghrsh/live2d_api)时大幅修改了[/get/index.php](https://github.com/fghrsh/live2d_api/blob/master/get/index.php)使其支持读取model3.json文件并重组为`../model/*`的形式。
以下是[我的代码](https://github.com/ChamberyChang/live2d_api/blob/master/get/index.php)：
```
<?php
isset($_GET['id']) ? $id = $_GET['id'] : exit('error');

require '../tools/modelList.php';
require '../tools/modelTextures.php';
require '../tools/jsonCompatible.php';

$modelList = new modelList();
$modelTextures = new modelTextures();
$jsonCompatible = new jsonCompatible();

$id = explode('-', $id);
$modelId = (int)$id[0];
$modelTexturesId = isset($id[1]) ? (int)$id[1] : 0;

$modelName = $modelList->id_to_name($modelId);

if (is_array($modelName)) {
    if ($modelTexturesId > 0) {
        $modelName = $modelName[$modelTexturesId-1];
    } else {
        $modelName = $modelName[0];
    }
    $pathv2 = '../model/'.$modelName.'/index.json';
    $modelMatch = preg_match('/\/[^\/]+$/',$modelName,$v3Match) ? $v3Match[0] : '/'.$modelName;
    $pathv3 = '../model/'.$modelName.$modelMatch.'.model3.json';
    if (file_exists($pathv2)){
        $json = json_decode(file_get_contents($pathv2), 1);
    } elseif (file_exists($pathv3)) {
        $json = json_decode(file_get_contents($pathv3), 1);
    }
    
} else {
    $pathv2 = '../model/'.$modelName.'/index.json';
    $modelMatch = preg_match('/\/[^\/]+$/',$modelName,$v3Match) ? $v3Match[0] : '/'.$modelName;
    $pathv3 = '../model/'.$modelName.$modelMatch.'.model3.json';
    if(file_exists($pathv2)){
        $json = json_decode(file_get_contents($pathv2), 1);
    } elseif (file_exists($pathv3)){
        $json = json_decode(file_get_contents($pathv3), 1);
    }
    
    if ($modelTexturesId > 0) {
        $modelTexturesName = $modelTextures->get_name($modelName, $modelTexturesId);
        if (isset($modelTexturesName)) {
            if (is_array($modelTexturesName)) {
                $json['textures'] = $modelTexturesName;
            } else {
                $json['textures'] = array($modelTexturesName);
            }
        } 
    }
}
if (file_exists($pathv2)) {
    foreach ($json['textures'] as $k => $texture)
	    $json['textures'][$k] = '../model/' . $modelName . '/' . $texture;

    $json['model'] = '../model/'.$modelName.'/'.$json['model'];
    if (isset($json['pose'])) $json['pose'] = '../model/'.$modelName.'/'.$json['pose'];
    if (isset($json['physics'])) $json['physics'] = '../model/'.$modelName.'/'.$json['physics'];

    if (isset($json['motions']))
        foreach ($json['motions'] as $k => $v) foreach($v as $k2 => $v2) foreach ($v2 as $k3 => $motion)
            if ($k3 == 'file' || $k3 == 'sound') $json['motions'][$k][$k2][$k3] = '../model/' . $modelName . '/' . $motion;

    if (isset($json['expressions']))
        foreach ($json['expressions'] as $k => $v) foreach($v as $k2 => $expression)
            if ($k2 == 'file') $json['expressions'][$k][$k2] = '../model/' . $modelName . '/' . $expression;

    header("Content-type: application/json");
    echo $jsonCompatible->json_encode($json);
} elseif (file_exists($pathv3)) {
    $json['FileReferences']['Moc'] = '../model/'.$modelName.'/'.$json['FileReferences']['Moc'];

    foreach ($json['FileReferences']['Textures'] as $k => $texture)
        $json['FileReferences']['Textures'][$k] = '../model/' . $modelName . '/' . $texture;
    
    if (isset($json['FileReferences']['Physics'])) $json['FileReferences']['Physics'] = '../model/'.$modelName.'/'.$json['FileReferences']['Physics'];

    if (isset($json['FileReferences']['Motions']))
        foreach ($json['FileReferences']['Motions'] as $k => $v) foreach($v as $k2 => $v2) foreach ($v2 as $k3 => $motion)
            if ($k3 == 'File' || $k3 == 'Sound') $json['FileReferences']['Motions'][$k][$k2][$k3] = '../model/' . $modelName . '/' . $motion;
    
    header("Content-type: application/json");
    echo $jsonCompatible->json_encode($json);
} else {
    echo "This is not '.json' OR 'model3.json'";
}
```
以碧蓝航线moc3模型赫敏为例，其目录为[ model/Azurlane/hemin_3 ](https://github.com/ChamberyChang/live2d_api/tree/master/model/Azurlane/hemin_3)，[model_list.json](https://github.com/ChamberyChang/live2d_api/blob/master/model_list.json)中指定为"Azurlane/hemin_3"，输出结果如下：
```
{
    "Version": 3,
    "FileReferences": {
        "Moc": "../model/Azurlane/hemin_3/hemin_3.moc3",
        "Textures": [
            "../model/Azurlane/hemin_3/textures/texture_00.png"
        ],
        "Physics": "../model/Azurlane/hemin_3/hemin_3.physics3.json",
        "Motions": {
            "": [
                {
                    "File": "../model/Azurlane/hemin_3/motions/main_1.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/main_2.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/mail.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/touch_head.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/login.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/idle.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/complete.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/main_3.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/touch_body.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/touch_special.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/home.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/mission.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/mission_complete.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/effect.motion3.json"
                },
                {
                    "File": "../model/Azurlane/hemin_3/motions/wedding.motion3.json"
                }
            ]
        }
    },
    "Groups": [
        {
            "Target": "Parameter",
            "Name": "LipSync",
            "Ids": [
                "ParamMouthOpenY"
            ]
        }
    ]
}
```
然而我在插件中调用api时发现其调取方式依然是cubism2的那一套模式，而没有起到直接填写model3.json地址应有的效果，不知能否修改wp-live2d中的live2d.js使其支持这一读取方式？

**Comment by jiangweifang** [comment]
其实我也在改写api这个部分，因为我是做.NET的，我读PHP代码有点不太适应，所以进度比较缓慢。
wp-live2d这个插件中比较重要的是live2d.js文件，我再live2d.js文件的工程中是这样判断当前读取的JSON是moc3还是moc的

`/**
 * 程序入口
 * @param {画板的ID} id 
 * @param {模型URL 用于获取JSON} modelurl 
 * @param {头部动作参数} headPos 
 * @param {缩放比例} zoom 
 * @param {V3版本触碰区域} hitAreaList 
 * @param {V4SDK的异步调用} sdkUrl 
 */
function loadlive2d(
        canvasId,
        modelurl,
        headPos,
        zoom = 1.0,
        hitAreaList = {},
        sdkUrl = 'https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js'
    ){
    head_pos = typeof headPos === 'undefined' ? 0.5 : headPos;
    hit_Area_List = hitAreaList;
    let pm = new PlatformManager();
    pm.loadString(modelurl,function(response){
        let jsonStr = JSON.parse(response);
        let modelStr = jsonStr['model'];
        let indexOfUrl = -1;
        let modelext;
        if(modelStr == undefined){
            indexOfUrl = modelurl.indexOf('model3.json');
        }else{
            modelext = modelStr.substring(modelStr.lastIndexOf('.') + 1);
        }
        switch(modelext){
            case 'moc':
                loadlive2dv2(canvasId,modelurl,zoom);
                break;
            case 'moc3':
                loadlive2dv3(canvasId,modelurl,zoom,sdkUrl);
                break;
            default:
                if(indexOfUrl > 0){
                    loadlive2dv3(canvasId,modelurl,zoom,sdkUrl);
                }else{
                    console.log("not model EXT. 没有获取到JSON中的model节点扩展名,应为moc|moc3,或传入相对路径的model3.json文件");
                }
                break;
        }
    });
}`

按照我的预计，如果使用live2d api的话 应该是可以对内容进行解析的，我稍后获取你的分支之后学习一下。

但是我这里有一个很重要的提示要和您说

[model/Azurlane/hemin_3/hemin_3.model3.json](https://github.com/ChamberyChang/live2d_api/blob/master/model/Azurlane/hemin_3/hemin_3.model3.json) 这里反馈出的内容，一定要重组Motions节点，Motions里面要包含3个动作标记，Idle（待机）、TapBody（触碰身体）、TapHead（触碰头部）
`{
  "Version": 3,
  "FileReferences": {
    "Moc": "hemin_3.moc3",
    "Textures": [
      "textures/texture_00.png"
    ],
    "Physics": "hemin_3.physics3.json",
    "Motions": {
      "Idle": [
        {
          "File": "motions/main_1.motion3.json"
        },
        {
          "File": "motions/main_2.motion3.json"
        },
        {
          "File": "motions/idle.motion3.json"
        },
        {
          "File": "motions/main_3.motion3.json"
        }
      ],
      "TapBody": [
        {
          "File": "motions/touch_special.motion3.json"
        },
        {
          "File": "motions/touch_body.motion3.json"
        }
      ],
      "TapHead": [
        {
          "File": "motions/touch_head.motion3.json"
        }
      ]
    }
  },
  "Controllers": {
    "ParamHit": {},
    "ParamLoop": {},
    "KeyTrigger": {},
    "EyeBlink": {
      "MinInterval": 500,
      "MaxInterval": 6000,
      "Items": [
        {
          "Id": "ParamEyeLOpen",
          "Min": 0.0,
          "Max": 1.0,
          "BlendMode": 2,
          "Input": 0
        },
        {
          "Id": "ParamEyeROpen",
          "Min": 0.0,
          "Max": 1.0,
          "BlendMode": 2,
          "Input": 0
        }
      ],
      "Enabled": true
    },
    "LipSync": {
      "Gain": 5.0,
      "Items": [
        {
          "Id": "ParamMouthOpenY",
          "Min": 0.0,
          "Max": 1.0,
          "Input": 0
        }
      ],
      "Enabled": true
    },
    "MouseTracking": {
      "SmoothTime": 0.15,
      "Enabled": true
    },
    "AutoBreath": {
      "Enabled": true
    },
    "ExtraMotion": {
      "Enabled": true
    },
    "Accelerometer": {
      "Enabled": true
    },
    "Microphone": {},
    "Transform": {},
    "FaceTracking": {
      "Enabled": true
    },
    "ParamValue": {},
    "PartOpacity": {},
    "ArtmeshOpacity": {},
    "ArtmeshColor": {},
    "ArtmeshCulling": {
      "DefaultMode": 0
    },
    "IntimacySystem": {}
  },
  "HitAreas": [
    {
      "Name": "Body",
      "Id": "TouchBody"
    },
    {
      "Name": "Head",
      "Id": "TouchHead"
    }
  ],
  "Options": {}
}`

**Comment by jiangweifang** [comment]
如果方便请加QQ 85838607 沟通

**Comment by ChamberyChang** [comment]
个人感觉可能这样子修改，还不如把api的get, add, switch, rand等都集成到本机wp插件上，在插件内做个自定义界面给使用者；
而api本身保留原结构，纯读取这样子，也可以走jsdelivr……
不过这样就脱离了调用api的范畴了，想想就麻烦，有空试试看能不能整合起来。

**Comment by jiangweifang** [comment]
我对于API这边还有后续扩展的打算，做成服务端和客户端的这种方式😂
