### ISSUE TITLE
请问现在这个插件是只有付费才能使用吗？

### ISSUE THREAD

**Issue by Haoxi2002** [jiangweifang/wp-live2d#13]
如题，找了一圈没有发现免费使用的按钮，请问是只有付费才能使用吗？是因为模型版权吗？如果有免费版，[本站](https://lsr2002.com/)开启插件后无法显示模型，期待并感谢作者的解答

**Comment by Haoxi2002** [comment]
我切换了一下插件版本，发现1.8.3可以使用，1.8.5什么都没显示，1.9.8版本只有框没有模型。
![image](https://github.com/jiangweifang/wp-live2d/assets/104291263/020e0148-cbc1-42be-af79-4326216294f2)
请问是要登录吗？但是登录链接ERROR，且无token。

**Comment by jiangweifang** [comment]
抱歉 因为我的疏忽，导致登录系统出现了一些异常，已经修复。

我刚才自测可用。以下是截图

![image](https://github.com/jiangweifang/wp-live2d/assets/38683169/a58443c6-e8ae-4f02-8e14-94721cd3a04f)

![image](https://github.com/jiangweifang/wp-live2d/assets/38683169/2b31ba39-2b82-4dfb-b94c-3260b8219877)

**Comment by Haoxi2002** [comment]
好的，谢谢您，他现在可以了，感谢您的贡献:-)
