### ISSUE TITLE
Wordpress5.8以后可能的兼容性问题

### ISSUE THREAD

**Issue by Daodanfd5** [jiangweifang/wp-live2d#16]
在我的机器上运行这个插件时更改设置无效，并且模型无法加载
wordpress版本:5.8.2
服务器环境：
Windows Server 2019+Nginx1.21.1+PHP-8.0.9&宝塔面板
低版本没有测试过，但是直接用autoload.js是可以放出来的，不过点击和拖拽啥的全部用不了

**Comment by jiangweifang** [comment]
已经对此进行了修复
