### ISSUE TITLE
请教一下哪里可以改模型的容器的大小

### ISSUE THREAD

**Issue by Mid9ts** [jiangweifang/wp-live2d#17]
或者哪里可以调整模型的高度。
自己加载了模型后发现如果缩放小了，模型会悬空；缩放大了头会被截去一部分。所以想知道怎么调整上面这些参数。
我是超级小白，自己捣鼓了半天也没效果。
多谢多谢！！

**Comment by jiangweifang** [comment]
下个版本将会加上移动模型位置的参数
