### ISSUE TITLE
请问如何添加自己的模型？

### ISSUE THREAD

**Issue by cola234** [jiangweifang/wp-live2d#18]
我有一个自己的模型，请问如何添加进去，需要自己搭建一个后端API吗

**Comment by VCE1** [comment]
> 我有一个自己的模型，请问如何添加进去，需要自己搭建一个后端API吗

https://github.com/jiangweifang/wp-live2d/issues/4

**Comment by jiangweifang** [comment]
如果可以，请直接在github上上传 直接使用路径即可
