### ISSUE TITLE
碧蓝航线moc3模型无法显示

### ISSUE THREAD

**Issue by railzy** [jiangweifang/wp-live2d#4]
> /live2d_api/model/hemin_3/hemin_3.model3.json

尝试读入本地碧蓝航线moc3模型，~~发现网页加载时相关文件都已读入但是不显示模型~~，发现网页加载时除了texture外所有文件都已经载入，不显示模型，并在console中输出以下错误

```
Uncaught (in promise) TypeError: Cannot set property 'time' of undefined
    at h.parse (live2d.js?ver=5.4.2:1)
    at Function.create (live2d.js?ver=5.4.2:1)
    at pi.loadMotion (live2d.js?ver=5.4.2:1)
    at live2d.js?ver=5.4.2:1
```

**Comment by jiangweifang** [comment]
我是从你的https://github.com/railzy/live2d_api 进入/live2d_api/model/hemin_3/hemin_3.model3.json ，但是你的 GitHub Pages 可能没有启用，你可能需要先启用 GitHub Pages 才可以访问此文件。
<img width="1430" alt="WechatIMG10" src="https://user-images.githubusercontent.com/38683169/88873980-8b081200-d250-11ea-9c83-946d3b95d374.png">
<img width="1439" alt="WechatIMG11" src="https://user-images.githubusercontent.com/38683169/88873987-8cd1d580-d250-11ea-9561-226bca82f5aa.png">

**Comment by jiangweifang** [comment]
正确打开Github Pages 后 https://cdn.jsdelivr.net/gh/railzy/live2d_api@master/model/kiritan/kiritan.model3.json 应可被访问

**Comment by jiangweifang** [comment]
我要检查一下这个问题，还请等待一段时间

**Comment by railzy** [comment]
之后我试了下别的方法，主要复制这篇  https://himehane.club/live2d_on_website/  博客的代码后实现了模型的正常运作。
另外找到的碧蓝航线模型成功实现例子有 https://github.com/imuncle/live2d
现有找到的碧蓝航线模型成功实现例子都使用了以下文件，而且好像只能运行Cubism 3的模型，无法和现有的Cubism2模型通用
pixi.min.js
live2dcubismcore.min.js
live2dcubismframework.js
live2dcubismpixi.js

另外live2dcubismcore.min.js似乎不允许再分发，可以考虑用下面的方法引入？
`<script src="https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js"></script>`

**Comment by jiangweifang** [comment]
根据http://www.live2d.com/en/download/cubism-sdk/download-web/ 的 Software License Agreement 规定，确实禁止分发，此项已修改为引用官网min.js，谢谢提醒避免律师函警告。

我的js也不是通用的，我只是在一些公用的地方做和合并，3.0的framework使用的是 [901d6c3](https://github.com/Live2D/CubismWebFramework/tree/901d6c356e9284e61b8b18a6e13bef8a57dc7b27) 

并且没有使用pixi

https://github.com/Yukariin/AzurLaneL2DViewer 项目对framework 进行了重构，在绘图填充部分使用了pixi.min.js，曾经试过，但是效果一般（是指开发效果上，而非显示效果），尤其是新老版本的合并上出现了很多问题，所以放弃了。

你的异常问题在于framework中有一个定义和你的模型不符合，我会通过你提供的可用实例进行对比，看是否需要对framework进行修改。

**Comment by jiangweifang** [comment]
去除 `motions` 的方法最简单粗暴，如果比较着急使用，可直接去除，model3.json 更新至：
https://github.com/jiangweifang/live2d_api/blob/live2d_api_v4/model/hemin_3/hemin_3.model3.json

**Comment by jiangweifang** [comment]
https://l2d.alg-wiki.com/ 系列使用的SDK3.3 以及Framework 不使用于官方Framework [901d6c3](https://github.com/Live2D/CubismWebFramework/tree/901d6c356e9284e61b8b18a6e13bef8a57dc7b27) ，所以本次更新对此部分代码进行了重写
- lapplive2dmanager.ts 的 onTap 方法：增加判断自定义的hitAreaList，用户可在WP后台对hitAreaList进行设置
- 对缩放算法进行修正，由原有lapplive2dmanager.ts 的 onUpdate 方法中计算 `projection.scale(zoom, (zoom * width) / height);` 改为使用`Framework/math/cubismmodelmatrix.ts` 中的构造方法`this.setHeight(zoom);` 进行控制，以确保缩放时触摸区域同比例缩放。
- 此版本为本地调整版本，下一个版本将直接修改API，从源头来保证生成的文件可被动作调用。
