### ISSUE TITLE
启动插件后手机端（移动端）滑动很卡，电脑端正常。我用的是WordPress5.4.2版本

### ISSUE THREAD

**Issue by jiangweifang** [jiangweifang/wp-live2d#5]
启动插件后手机端（移动端）滑动很卡，电脑端正常。我用的是WordPress5.4.2版本

_Originally posted by @ydecl in https://github.com/jiangweifang/wp-live2d/issues/2#issuecomment-668050038_

此bug转为moc3问题，moc3内存占用率过高，导致页面卡顿，内存使用量超过18mb
![1597131656266](https://user-images.githubusercontent.com/38683169/89870862-0ff81180-dbe9-11ea-97e3-45e1e1b6f6fb.jpg)

**Comment by jiangweifang** [comment]
我康康 因为我会选择手机端不显示动画，一直没有注意这个问题

**Comment by jiangweifang** [comment]
如果方便请告知您使用的手机型号 和浏览器

**Comment by ydecl** [comment]
vivo x9s  ,QQ浏览器、谷歌浏览器、自带浏览器都试过

**Comment by ydecl** [comment]
修复了吗？(●'◡'●)

**Comment by ydecl** [comment]
修复了吗？还是卡

**Comment by jiangweifang** [comment]
卡顿是很难修复的问题，需要时间观察，最近在处理moc3模型动作问题，所以卡顿问题可能要延后解决

**Comment by ydecl** [comment]
没事，我只是问问。因为我看到插件有更新(●'◡'●)

**Comment by jiangweifang** [comment]
我在自行检查的时候发现了moc3模型在loadMotion方法中内存消耗较大的问题，但是需要更准确的定位，请提供你的网站和你使用的模型给我，谢谢。

**Comment by ydecl** [comment]
http://bk.wuyouheike.top/。模型？没有呀

**Comment by ydecl** [comment]
http://bk.wuyouheike.top/
模型？是只模型ID?
如果是模型id所有都卡

**Comment by ydecl** [comment]
http://bk.wuyouheike.top/
模型？是指模型ID?
如果是模型id所有都卡

**Comment by jiangweifang** [comment]
刚才检查了一下网页消耗情况，目前moc模型的读取消耗比moc3模型读取要快很多，虽然在自查的时候发现了内存消耗，但是和moc模型无关，是moc3模型预加载动作文件时会非常消耗性能。稍后我会对moc3模型消耗做出一定优化。对于你的卡顿可能暂时无法解决，感谢支持，下图是你网站加载时使用的内存情况。
加载耗时128.95 ms(104.22 ms network transfer + 24.74 ms resource loading)
JS堆内存：1.7-7.4mb
<img width="1439" alt="WechatIMG27" src="https://user-images.githubusercontent.com/38683169/89869704-4f256300-dbe7-11ea-8fe4-3cd43dc2a291.png">

**Comment by ydecl** [comment]
诶
