### ISSUE TITLE
1.7.5 使用问题

### ISSUE THREAD

**Issue by aquausora** [jiangweifang/wp-live2d#7]
主题是 [Sakura](https://github.com/mashirozx/Sakura)，安装后网页仍无法显示 Live 2d 模型。

Console 的报错：

![20200816023432](https://user-images.githubusercontent.com/57339353/90319266-0c59e700-df69-11ea-8e8c-bb7f62d5fb93.png)

![39UUHLZGR7PATX8D42OJLGW](https://user-images.githubusercontent.com/57339353/90319304-6b1f6080-df69-11ea-8733-101d5c8dd6a7.png)

**Comment by aquausora** [comment]
你好，更新1.7.6之后控制台报Jquery异常。
![微信图片_20200904120125](https://user-images.githubusercontent.com/57339353/92198224-6550d700-eea6-11ea-8957-63a5fc3bc6fd.png)

**Comment by jiangweifang** [comment]
你网站是啥 我去康康

**Comment by aquausora** [comment]
那还有劳大佬去检查一下了
https://www.champhoon.xyz/

**Comment by jiangweifang** [comment]
> 那还有劳大佬去检查一下了
> https://www.champhoon.xyz/

请尝试给live2d插件中wordpress-live2d.php文件第29行`add_action( 'get_header', 'live2D_style' );` 替换为 `add_action( 'wp_head', 'live2D_style' );` 之后再试试

**Comment by aquausora** [comment]
我发现问题源头了，这个插件与 WP Editor.md 插件存在冲突，不过经我测试，本来Live2D 看板娘前端 HTML 源码也是与 WP Editor.md 插件存在冲突的，这个冲突会导致看板娘无法显示以及某些使用 WP Editor.md 插件写的文章无法正常显示，不过只要把 WP Editor.md 插件停用问题就解决了。

**Comment by jiangweifang** [comment]
感谢提醒，我之前也用WP Editor 我回头再试试
