### ISSUE TITLE
关于某些主题手机端问题

### ISSUE THREAD

**Issue by Project-458** [jiangweifang/wp-live2d#8]
希望wp live2d 作者能给插件加一个 判断移动端用户是否加载插件功能 说实话有些主题可能不适用，在某些主题上使用live2d插件，利用移动端访问翻滚条整个都很难移动整个页面都很卡，火狐浏览器还可以其他浏览器就....，希望能加一个这个功能，避免一些移动端用户访问的时候加载这个插件造成的卡顿和页面问题，目前我的主题使用了这个live2d插件移动端访问根本没法正常浏览，页面拖拽卡顿现象太严重，判断移动端访问才解决了这个问题，最后还是希望作者能够加这个功能！真的很希望！最后祝作者越做越好，身体健康！

**Comment by DogeZen** [comment]
我的情况是只要在手机端点击关闭live2d，或者指定了面页小于指定宽度隐藏看板娘，让手机端隐藏live2d，手机浏览器会直接崩溃

**Comment by DogeZen** [comment]
建议，面页小于指定宽度**隐藏看板娘**，改为面页小于指定宽度**不加载插件**，不然移动端会直接卡顿到崩溃

**Comment by jiangweifang** [comment]
感谢 DogeZen 我会修改为小于指定宽度不加载插件

**Comment by jiangweifang** [comment]
1.7.6 对此处理如下：
```
function initModel(waifuPath, settingsJson) {
//--------------------------------略--------------------------------
window.waifuResize = function() { $(window).width() <= live2d_settings.waifuMinWidth ? $(".waifu").hide() : $(".waifu").show(); };
    if (live2d_settings.waifuMinWidth != 0) { 
        if($(window).width() <= live2d_settings.waifuMinWidth){
            $(".waifu").hide();
            return;
        }else{
            $(".waifu").show(); 
        }
        $(window).resize(function() {waifuResize()});
    }
//--------------------------------略--------------------------------
}
```
`waifuResize`函数被`$(window).resize(function() {waifuResize()});`调用是为了在比较大屏幕加载了看板娘后，缩小再放大看板娘可恢复显示所使用。
