### ISSUE TITLE
能否加一个显示隐藏看板娘的配置

### ISSUE THREAD

**Issue by wenhongvip** [jiangweifang/wp-live2d#9]
首先谢谢开发出这么棒的插件，但是看板娘太占资源了，可以在前台加个控制看板娘的图标按钮嘛，访客可以根据情况是否启用看板娘

**Comment by jiangweifang** [comment]
这个我得考虑一下如何处理，我根据之前的issues理解其实不是看板娘渲染导致的，应该是在加载JS之后导致资源消耗了，我担心关闭功能不一定可以彻底解决这个问题，另外有隐藏看板娘按钮哦~

**Comment by jiangweifang** [comment]
关于这个事情我想到一个更好的解决方法，1.7.8版本应该可以更新
