### ISSUE TITLE
gpt 无法使用

### ISSUE THREAD

**Issue by HolmesZhao** [jiangweifang/wp-live2d#9]
<img width="298" alt="image" src="https://user-images.githubusercontent.com/19728934/229330370-bf3d68d8-a22c-47ad-aef9-df9f44bfadec.png">

无法打字也无法发送

**Comment by jiangweifang** [comment]
请提供网址或者付费账户的邮箱

**Comment by HolmesZhao** [comment]
> 请提供网址或者付费账户的邮箱

GPT 是付费用户才能用的呀? 付费后自行配置 apikey?

**Comment by jiangweifang** [comment]
是的~
